const state={rows:[],headers:[],model:null,charts:{},fileData:null,fileName:''};
const STATUS={completed:'GERENCIOU',partial:'PARCIAL',pending:'PENDENTE',none:'SEM REGISTRO'};
const STATUS_LABELS={GERENCIOU:'Concluído',PARCIAL:'Parcial',PENDENTE:'Pendente','SEM REGISTRO':'Sem registro'};
const $=id=>document.getElementById(id);
function normalizeText(v){return String(v??'').trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').toUpperCase()}
function normalizeHeader(v){return normalizeText(v).replace(/[^A-Z0-9]+/g,' ').trim()}
function cleanCell(v){if(v==null)return '';if(typeof v==='number')return Number.isFinite(v)?v:'';return String(v).trim()}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function findField(headers,candidates){const list=headers.map(key=>({key,value:normalizeHeader(key)}));for(const c of candidates){const hit=list.find(x=>x.value===c||x.value.includes(c));if(hit)return hit.key}return ''}
function looksLikeHeader(row){return Object.keys(row).map(normalizeHeader).some(h=>/TUTOR|ORDEM|STATUS|SITUACAO|GERENCIAMENTO|ALUNO|PROFESSOR/.test(h))}
function parseFile(data,name){const wb=XLSX.read(data,{type:'array',cellDates:true});if(!wb.SheetNames.length)return null;const sheetName=wb.SheetNames.find(n=>normalizeHeader(n)==='02 SEMESTRE')||wb.SheetNames[0];const sheet=wb.Sheets[sheetName];const base={defval:'',raw:false};let rows=XLSX.utils.sheet_to_json(sheet,base);if(!rows.length)return null;if(!looksLikeHeader(rows[0])){const raw=XLSX.utils.sheet_to_json(sheet,{...base,range:3});if(raw.length&&looksLikeHeader(raw[0]))rows=raw;else{const all=XLSX.utils.sheet_to_json(sheet,base);const i=all.findIndex(looksLikeHeader);if(i>=0)rows=XLSX.utils.sheet_to_json(sheet,{...base,range:i})}}if(!rows.length)return null;const headers=Object.keys(rows[0]);return{sheetName,headers,rows:rows.map(r=>Object.fromEntries(headers.map(h=>[h,cleanCell(r[h])])))} }
function normalizeStatus(v){const t=normalizeText(v);if(!t||['NAN','NONE','NULL','NA','_EMPTY','-'].includes(t))return STATUS.none;if(t==='X'||/PENDENTE|AGUARDANDO|NAO GERENCIADO/.test(t))return STATUS.pending;if(/PARCIAL/.test(t))return STATUS.partial;if(/GERENCIAD|GERENCIOU|OK|REALIZAD|CONCLUID|ATENDID|FEITO|SIM/.test(t))return STATUS.completed;return STATUS.none}
function buildModel(rows,headers){const tutorField=findField(headers,['TUTOR','PROFESSOR','RESPONSAVEL','ALUNO']);const statusField=findField(headers,['STATUS','SITUACAO','ESTADO','GERENCIAMENTO']);const dateField=findField(headers,['DATA','PERIODO','MES','DATA DO ATENDIMENTO']);const orderFields=headers.filter(h=>{const n=normalizeHeader(h);return n.includes('ORDEM')||/^0?[1-9]$/.test(n)||/^ORDEM\s+0?[1-9]+/.test(n)});const records=rows.map(row=>{const values=orderFields.map(h=>row[h]).filter(v=>String(v??'').trim()!=='');const status= statusField?normalizeStatus(row[statusField]):values.some(v=>normalizeStatus(v)===STATUS.pending)?STATUS.pending:values.some(v=>normalizeStatus(v)===STATUS.partial)?STATUS.partial:values.length&&values.every(v=>normalizeStatus(v)===STATUS.completed)?STATUS.completed:STATUS.none;return{...row,_status:status,_tutor:row[tutorField]||'SEM TUTOR',_date:row[dateField]||'',_values:values}});return{records,headers,tutorField,statusField,dateField,orderFields}}
function renderCards(records){const total=records.length,done=records.filter(r=>r._status===STATUS.completed).length,partial=records.filter(r=>r._status===STATUS.partial).length,tutors=new Set(records.map(r=>String(r._tutor))).size;const pct=total?Math.round(done/total*100):0;const cards=[['📊','REGISTROS',total,'Linhas registradas'],['✅','CONCLUÍDOS',`${pct}%`,`${done} concluídos`],['👤','TUTORES',tutors,'Itens únicos no conjunto'],['⏳','PENDENTES',records.filter(r=>r._status===STATUS.pending).length,`${partial} parciais`]];$('cardsContainer').innerHTML=cards.map(c=>`<article class="stat-card"><div class="stat-icon">${c[0]}</div><div><p class="stat-label">${c[1]}</p><p class="stat-value">${c[2]}</p><p class="subtitle">${c[3]}</p></div></article>`).join('')}
function statusClass(s){return s===STATUS.completed?'status-completed':s===STATUS.partial?'status-partial':s===STATUS.pending?'status-pending':'status-none'}
function renderTable(){const query=normalizeText($('searchInput').value),filter=$('statusFilter').value;const rows=state.rows.filter(r=>(!filter||r._status===filter)&&(!query||state.headers.some(h=>normalizeText(r[h]).includes(query))));$('theadTable').innerHTML=`<tr>${state.headers.map(h=>`<th>${escapeHtml(h)}</th>`).join('')}<th>Status</th></tr>`;$('tbodyTable').innerHTML=rows.slice(0,100).map(r=>`<tr>${state.headers.map(h=>`<td>${escapeHtml(r[h])}</td>`).join('')}<td><span class="status-pill ${statusClass(r._status)}">${STATUS_LABELS[r._status]}</span></td></tr>`).join('');$('emptyState').style.display=rows.length?'none':'block';$('rowCount').textContent=`${rows.length} de ${state.rows.length} registros`}
function chartOptions(){return{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{usePointStyle:true,boxWidth:8,font:{size:11}}}},scales:{x:{grid:{display:false},ticks:{font:{size:10}}},y:{beginAtZero:true,ticks:{precision:0},grid:{color:'#edf1f7'}}}}}
function renderCharts(records){Object.values(state.charts).forEach(c=>c?.destroy());state.charts={};const colors=['#22c55e','#f97316','#ef4444','#94a3b8'];const counts=Object.values(STATUS).map(s=>records.filter(r=>r._status===s).length);state.charts.status=new Chart($('chartStatus'),{type:'doughnut',data:{labels:Object.values(STATUS_LABELS),datasets:[{data:counts,backgroundColor:colors,borderWidth:3,borderColor:'#fff'}]},options:{responsive:true,maintainAspectRatio:false,cutout:'62%',plugins:{legend:{position:'bottom',labels:{usePointStyle:true,boxWidth:8,font:{size:11}}}}}});const tutor={};records.forEach(r=>{tutor[r._tutor]=(tutor[r._tutor]||0)+1});const tutors=Object.entries(tutor).sort((a,b)=>b[1]-a[1]).slice(0,12);state.charts.tutors=new Chart($('chartDistribuicao'),{type:'bar',data:{labels:tutors.map(x=>String(x[0]).slice(0,18)),datasets:[{data:tutors.map(x=>x[1]),backgroundColor:'#315fe9',borderRadius:6}]},options:{...chartOptions(),plugins:{legend:{display:false}}}});const dates={};records.forEach(r=>{if(r._date)dates[r._date]=(dates[r._date]||0)+1});const timeline=Object.entries(dates);state.charts.timeline=new Chart($('chartTimeline'),{type:'line',data:{labels:timeline.map(x=>x[0]),datasets:[{label:'Registros',data:timeline.map(x=>x[1]),borderColor:'#315fe9',backgroundColor:'rgba(49,95,233,.12)',fill:true,tension:.35,pointRadius:3}]},options:chartOptions()})}
function loadData(data,name){try{const parsed=parseFile(data,name);if(!parsed)throw new Error('Não encontrei linhas válidas.');state.model=buildModel(parsed.rows,parsed.headers);state.rows=state.model.records;state.headers=parsed.headers;state.fileData=data;state.fileName=name;$('arquivoNome').textContent=name;$('sheetName').textContent=`Aba: ${parsed.sheetName}`;$('lastUpdate').textContent=`Atualizado agora • ${state.rows.length} registros`;$('statusFilter').innerHTML='<option value="">Todos os status</option>'+Object.values(STATUS).map(s=>`<option value="${s}">${STATUS_LABELS[s]}</option>`).join('');renderCards(state.rows);renderTable();renderCharts(state.rows)}catch(e){alert(`Não foi possível ler a planilha.\n\n${e.message}`);console.error(e)}}
$('fileInput').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=ev=>loadData(ev.target.result,file.name);reader.readAsArrayBuffer(file)});$('searchInput').addEventListener('input',renderTable);$('statusFilter').addEventListener('change',renderTable);$('exportBtn').addEventListener('click',()=>{if(!state.rows.length){alert('Carregue uma planilha antes de exportar.');return}window.print()});$('recarregarBtn').addEventListener('click',()=>{if(state.fileData)loadData(state.fileData,state.fileName);else alert('Ainda não há uma planilha carregada.')});
