const XLSX_URL='GERENCIAMENTO CONTROLE JACKSON.xlsx';
const state={rows:[],filtered:[],charts:{},orders:[]};
const COLORS={GERENCIOU:'#16a34a',PARCIAL:'#f59e0b',PENDENTE:'#dc2626','SEM REGISTRO':'#94a3b8'};
const norm=v=>String(v??'').trim().toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const clean=v=>String(v??'').trim();
function classify(v){const x=norm(v);if(!x)return 'SEM REGISTRO';if(x==='X'||x.includes('PENDENTE')||x.includes('AGUARDANDO'))return 'PENDENTE';if(x.includes('PARCIAL'))return 'PARCIAL';if(x.includes('GERENC')||x.includes('REALIZ')||x.includes('CONCL')||x==='OK'||x.includes('FEITO'))return 'GERENCIOU';return x;}
function meaningfulColumns(headers){return headers.filter(h=>clean(h)&&!/^__EMPTY(_\d+)?$/i.test(clean(h)));}
function findTutor(headers){const words=['TUTOR','NOME','RESPONSAVEL','RESPONSÁVEL'];return headers.find(h=>words.some(w=>norm(h).includes(norm(w))))||headers[0];}
function orderName(h){const m=norm(h).match(/ORDEM\s*0*(\d+)/);return m?`ORDEM ${m[1].padStart(2,'0')}`:null;}
function parseWorkbook(buf){const wb=XLSX.read(buf,{type:'array',cellDates:true});const sheet=wb.SheetNames.find(s=>norm(s)==='02SEMESTRE')||wb.SheetNames[0];const ws=wb.Sheets[sheet];const raw=XLSX.utils.sheet_to_json(ws,{range:3,defval:'',raw:false});if(!raw.length)throw Error('A aba 02semestre não possui dados a partir da linha 4.');const headers=meaningfulColumns(Object.keys(raw[0]));const tutor=findTutor(headers);const ordens=headers.map(orderName).filter(Boolean);const rows=raw.map(r=>{const o={TUTOR:clean(r[tutor]),STATUS_TUTOR:'',ORDEM:'GERAL',GERENCIAMENTO:'SEM REGISTRO'};const status=headers.find(h=>['STATUS DO TUTOR','SITUACAO DO TUTOR','CATEGORIA'].some(x=>norm(h).includes(norm(x))));if(status)o.STATUS_TUTOR=clean(r[status]);const ordemCols=headers.filter(h=>orderName(h));if(ordemCols.length){return ordemCols.map(c=>({...o,ORDEM:orderName(c),GERENCIAMENTO:classify(r[c])}));}return [{...o,GERENCIAMENTO:classify(r[tutor])}];}).flat().filter(r=>r.TUTOR&&!/^TUTOR$|^NOME$/i.test(r.TUTOR));return {sheet,rows,orders:[...new Set(ordens)]};}
function filtered(){const o=document.getElementById('ordemFiltro').value,s=document.getElementById('statusFiltro').value,q=norm(document.getElementById('tutorFiltro').value);return state.rows.filter(r=>(o==='TODAS'||r.ORDEM===o)&&(s==='TODOS'||r.GERENCIAMENTO===s)&&(!q||norm(r.TUTOR).includes(q)));}
function metricCards(rows){const total=new Set(rows.map(r=>r.TUTOR)).size;const count=s=>new Set(rows.filter(r=>r.GERENCIAMENTO===s).map(r=>r.TUTOR)).size;const data=[['TOTAL DE TUTORES',total,'👥','base'],['GERENCIARAM',count('GERENCIOU'),'✓',`${total?((count('GERENCIOU')/total)*100).toFixed(1):0}% do total`],['GERENCIAMENTO PARCIAL',count('PARCIAL'),'◐',`${total?((count('PARCIAL')/total)*100).toFixed(1):0}% do total`],['PENDENTES',count('PENDENTE'),'!',`${total?((count('PENDENTE')/total)*100).toFixed(1):0}% do total`],['SEM REGISTRO',count('SEM REGISTRO'),'—',`${total?((count('SEM REGISTRO')/total)*100).toFixed(1):0}% do total`]];document.getElementById('cardsContainer').innerHTML=data.map(x=>`<article class="stat-card"><div class="stat-icon">${x[2]}</div><p>${x[0]}</p><h3>${x[1].toLocaleString('pt-BR')}</h3><span>${x[3]}</span></article>`).join('');}
function chart(id,config){if(state.charts[id])state.charts[id].destroy();state.charts[id]=new Chart(document.getElementById(id),config);}
function renderCharts(rows){const statuses=['GERENCIOU','PARCIAL','PENDENTE','SEM REGISTRO'];const values=statuses.map(s=>rows.filter(r=>r.GERENCIAMENTO===s).length);chart('chartStatus',{type:'doughnut',data:{labels:statuses,datasets:[{data:values,backgroundColor:statuses.map(s=>COLORS[s])}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}});const orders=[...new Set(rows.map(r=>r.ORDEM))];const managed=orders.map(o=>rows.filter(r=>r.ORDEM===o&&r.GERENCIAMENTO==='GERENCIOU').length);chart('chartOrdem',{type:'bar',data:{labels:orders,datasets:[{label:'Gerenciados',data:managed,backgroundColor:'#2563eb',borderRadius:7}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}}});chart('chartComparativo',{type:'bar',data:{labels:orders,datasets:['GERENCIOU','PARCIAL','PENDENTE'].map(s=>({label:s,data:orders.map(o=>rows.filter(r=>r.ORDEM===o&&r.GERENCIAMENTO===s).length),backgroundColor:COLORS[s],borderRadius:5}))},options:{responsive:true,maintainAspectRatio:false,scales:{y:{beginAtZero:true}}}});}
function renderTable(rows){const grouped={};rows.forEach(r=>{grouped[r.TUTOR]??={TUTOR:r.TUTOR,STATUS_TUTOR:r.STATUS_TUTOR};grouped[r.TUTOR][r.ORDEM]=r.GERENCIAMENTO;});const orders=[...new Set(rows.map(r=>r.ORDEM))];const headers=['TUTOR','STATUS_TUTOR',...orders];document.getElementById('theadTable').innerHTML=`<tr>${headers.map(h=>`<th>${h.replace('STATUS_TUTOR','SITUAÇÃO DO TUTOR')}</th>`).join('')}</tr>`;document.getElementById('tbodyTable').innerHTML=Object.values(grouped).map(r=>`<tr>${headers.map(h=>{const v=r[h]||'—';return `<td><span class="badge ${norm(v).replaceAll(' ','-')}">${v}</span></td>`}).join('')}</tr>`).join('');document.getElementById('contadorTabela').textContent=`${Object.keys(grouped).length} tutores encontrados`;}
function render(){state.filtered=filtered();metricCards(state.filtered);renderCharts(state.filtered);renderTable(state.filtered);}
async function load(){try{const res=await fetch(XLSX_URL);if(!res.ok)throw Error('Planilha não encontrada.');const parsed=parseWorkbook(await res.arrayBuffer());state.rows=parsed.rows;state.orders=parsed.orders;const select=document.getElementById('ordemFiltro');select.innerHTML='<option value="TODAS">Todas as ordens</option>'+state.orders.map(o=>`<option>${o}</option>`).join('');document.getElementById('arquivoNome').textContent=parsed.sheet;document.getElementById('ultimaAtualizacao').textContent=`${state.rows.length} registros analisados`;render();}catch(e){document.getElementById('cardsContainer').innerHTML=`<article class="stat-card error-card"><p>ERRO</p><h3>${e.message}</h3></article>`;}}
document.getElementById('recarregarBtn').onclick=load;document.getElementById('ordemFiltro').onchange=render;document.getElementById('statusFiltro').onchange=render;document.getElementById('tutorFiltro').oninput=render;document.getElementById('limparFiltros').onclick=()=>{document.getElementById('ordemFiltro').value='TODAS';document.getElementById('statusFiltro').value='TODOS';document.getElementById('tutorFiltro').value='';render();};window.addEventListener('DOMContentLoaded',load);
